spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
    minIdle: 2
    maxIdle: 5
    initialSize: 5
    removeAbandoned: true
    maxActive: 10